---
title: Verdade Proibida
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
    read_time: false
    comments: false
    share: false
    related: false
minimal_mistakes_skin: default
locale: pt-BR
title_separator: "|"
name: Marcus Coelho
description: Resistindo, informando e denunciando a Nova Ordem Mundial
url: https://verdadeproibida.netlify.com
baseurl: 
repository: verdadeproibida/site
teaser: 
breadcrumbs: false
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: vproibida
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields: 
  branch: 
  commitMessage: 
  filename: 
  format: 
  moderation: 
  path: 
  requiredFields: 
  transforms:
    email: 
  generatedFields:
    date:
      type: 
      options:
        format: 
reCaptcha:
  siteKey: 
  secret: 
atom_feed:
  path: 
search: true
remote_theme: mmistakes/minimal-mistakes
google_site_verification: 
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: proibidaverdade
facebook:
  username: vproibida
  app_id: 
  publisher: 
og_image: 
social:
  type: Person
  name: Marcus Coelho
  links: 
analytics:
  provider: google
  google:
    tracking_id: UA-111427945-1
author:
  name: Marcus Coelho
  avatar: "/assets/images/koala.jpg"
  bio: Advogando contra a Nova Ordem Mundial
  location: Brasil
  email: vproibida@gmail.com
  facebook: https://www.facebook.com/vproibida/
  twitter: https://twitter.com/proibidaverdade
  reddit: https://www.reddit.com/user/verdadeproibida/
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 8
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
    permalinks:
      category: "/categories/:name/"
      tag: "/tags/:name/"
compress_html:
  clippings: all
  ignore:
    envs: production
